Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,59 +1,23 @@
 version: 2.1
 
 orbs: 
-    slack: circleci/slack@4.12.1
+    slack: circleci/slack@4.10.1
 
 commands:
-  install_awscli:
-    description: Install AWScli
-    steps:
-      - run:
-          name: Install AWS CLI v2
-          command: |
-            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-            unzip awscliv2.zip
-            sudo ./aws/install
-  install_ansible:
-    description: Install Ansible latest
-    steps:
-      - run:
-          name: Install Ansible latest
-          command: |
-            sudo apt update
-            sudo apt install software-properties-common
-            sudo add-apt-repository --yes --update ppa:ansible/ansible
-            sudo apt install ansible
-            sudo apt install ansible -y
-  install_nodejs:
-    description: Install Node.js 16
-    steps:
-      - run:
-          name: Install Node.js 16
-          command: |
-            curl fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
-            sudo apt-get install -y node.js
-  install_dependencies:
-    description: Install dependencies
-    steps:
-      - run:
-          name: Install dependencies
-          command: |
-            yum install -y tar gzip
-  destroy-environment:
+  destroy_environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
       Workflow_ID:
         type: string
-        default: ${CIRCLE_WORKFLOW_ID:0:7}   
+        default: ${CIRCLE_WORKFLOW_ID:0:5}
     steps:
       - run:
-          name: Destroy environments
+          name: Destroy environment
           when: on_fail
           command: |
-            echo "Destroying environment: << parameters.Workflow_ID >> "          
-            aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.Workflow_ID >>
+            aws cloudformation delete-stack --stack-name backend-${CIRCLE_WORKFLOW_ID:0:5}
             aws s3 rm s3://udapeople-<<parameters.Workflow_ID>> --recursive
-            aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.Workflow_ID >>
+            aws cloudformation delete-stack --stack-name frontend-<< parameters.Workflow_ID >>
   notify_on_failure:
       steps:
         - slack/notify:
@@ -67,33 +31,34 @@ commands:
             channel: $SLACK_DEFAULT_CHANNEL
             template: success_tagged_deployment_1
 
+
   revert-migrations:
-    description: Revert the last migration if successfully run in the current workflow.
+    description: Revert the last migration
     parameters:
       Workflow_ID:
         type: string
         default: ${CIRCLE_WORKFLOW_ID:0:7}
-
     steps:
       - run:
           name: Revert migrations
-          when: on_fail        # Add when this will run
+          when: on_fail
           command: |
-            SUCCESS=$(curl --insecure  https://kvdb.io/rHHiyAHyXFsG4EDRPANWj/migration_<< parameters.Workflow_ID >>)
-            
+            SUCCESS=$(curl --insecure  https://kvdb.io/${KVDB_BUCKET}/migration_<< parameters.Workflow_ID >>)
+            echo "$SUCCESS"
             # Logic for reverting the database state
             if (( $SUCCESS == 1 ));
             then
-              echo "$SUCCESS"
               cd ~/project/backend
               npm install
-              npm run migrations:revert
+              npm run migration:revert
             fi
-                        
+            
 jobs:
+
   build-frontend:
     docker:
       - image: circleci/node:13.8.0
+    # working_directory: ~/project/.circleci/ansible/inventory.txt
     steps:
       - checkout
       - restore_cache:
@@ -101,9 +66,9 @@ jobs:
       - run:
           name: Build front-end
           command: |
+            exit 0
             cd frontend
-            npm install
-            npm run build
+            npm run build:prod
       - save_cache:
           paths: [frontend/node_modules]
           key: frontend-build
@@ -137,7 +102,7 @@ jobs:
           command: |
             cd frontend
             npm install
-            npm install oauth-sign
+            npm iinstall oauth-sign
             # npm run build
             npm run test
                 
@@ -151,8 +116,8 @@ jobs:
       - run:
           name: Test Back-end
           command: |
+            exit 0
             cd backend
-            npm install
             npm run test
             
   scan-frontend:
@@ -165,11 +130,8 @@ jobs:
       - run:
           name: Scan front-end
           command: |
-             cd frontend
-             npm install
-             npm audit fix --force --audit-level=critical
-             npm audit fix --force --audit-level=critical
-             npm audit --audit-level=critical
+            exit 0
+            npm audit
   scan-backend:
     docker:
       - image: circleci/node:13.8.0
@@ -180,36 +142,34 @@ jobs:
       - run:
           name: Scan Back-end
           command: |
-             cd backend
-             npm install
-             npm audit fix --force --audit-level=critical
-             npm audit fix --force --audit-level=critical
-             npm audit --audit-level=critical
-             
+            exit 0
+            npm audit
   deploy-infrastructure:
     docker:
       - image: amazon/aws-cli
     steps:
       - checkout
-    #  - install_awscli
-      - install_dependencies
-
       - run:
-           name: Ensure back-end infrastructure exists
-           command: |
-             aws cloudformation deploy \
-               --template-file .circleci/files/backend.yml \
-               --tags project=udapeople \
-               --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-               --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7}
+          name: Install dependencies
+          command: |
+            yum install -y tar gzip
+      # - run:
+      #     name: Ensure back-end infrastructure exists
+      #     command: |
+      #       aws cloudformation deploy \
+      #         --template-file .circleci/files/backend.yml \
+      #         --tags project=udapeople \
+      #         --stack-name "backend" \
+      #         --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:5}
+
       - run:
           name: Ensure front-end infrastructure exist
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/frontend.yml \
               --tags project=udapeople \
-              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
+              --stack-name "frontend-${CIRCLE_WORKFLOW_ID:0:5}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:5}"
       - run:
           name: Add back-end ip to ansible inventory
           command: |
@@ -218,55 +178,49 @@ jobs:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
-      - destroy-environment
-      - notify_on_failure      
-
+#       # Here's where you will add some code to rollback on failure      
+      # - destroy_environment
   configure-infrastructure:
     docker:
-      - image:  mareimorsy/aws-node
+      - image: mareimorsy/aws-node
     steps:
       - checkout
-  #    - install_awscli
-    # - install_ansible
-    #  - install_dependencies            
       - add_ssh_keys:
           fingerprints: ["79:1b:93:8b:e3:ca:fe:be:61:26:31:42:dd:c0:51:cb"]
+      # - run:
+      #     name: "Install Dependencies"
+      #     command: |
+      #       apk add ansible gzip openssh-client
       - attach_workspace:
-           at: ~/
+          at: ~/
       - run:
           name: Configure server
           command: |
-            ls
-            pwd
             cd .circleci/ansible
             aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> inventory.txt
             cat inventory.txt
-            ansible-playbook -i inventory.txt configure-server.yml -vv
-          #  ansible-playbook -i inventory.txt prometheus-exporter.yml -vv
+            ansible-playbook -i inventory.txt configure-server.yml
       # Here's where you will add some code to rollback on failure      
-      # - destroy-environment     
-
 
   run-migrations:
     docker: 
-      - image:  mareimorsy/aws-node
+      - image: mareimorsy/aws-node
+
     steps:
       - checkout
       - run:
           name: Run migrations
           command: |
+            export TYPEORM_HOST=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
             cd backend
             npm install
             npm run premigrations
-            npm run migrations > migrations_dump.txt
-      - run:
-          name: Send migration results to kvdb.io
-          command: |
-            curl --insecure -d '1'  https://kvdb.io/rHHiyAHyXFsG4EDRPANWj/migration_${CIRCLE_WORKFLOW_ID:0:7}
-            echo ${CIRCLE_WORKFLOW_ID:0:7}
-            echo https://kvdb.io/rHHiyAHyXFsG4EDRPANWj
-      - destroy-environment
-      - revert-migrations
+            npm run migrations
+      # - run:
+      #     name: Send migration results to memstash
+      #     command: |
+      #       # Your code here
+      #       exit 1
      # Here's where you will add some code to rollback on failure      
 
   deploy-frontend:
@@ -274,110 +228,64 @@ jobs:
       - image: mareimorsy/aws-node
     steps:
       - checkout
-#      - install_awscli
-#      - install_nodejs
-    #  - install_ansible
-      - restore_cache:
-          keys: [frontend-deps]
-      - attach_workspace:
-           at: ~/          
-      - run:
-          name: Install dependencies
-          command: |
-            cd frontend
-            npm install
       - run:
           name: Deploy Frontend
           command: |
-            export BACKEND_PUBLIC_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --query=Reservations[].Instances[].PublicIpAddress --output text)
-            echo "API_URL=http://$BACKEND_PUBLIC_IP:3030" 
+            export BACKEND_PUBLIC_IP=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+             echo "API_URL=http://$BACKEND_PUBLIC_IP:3030" 
             # Build the frontend
             cd frontend
             echo "API_URL=http://$BACKEND_PUBLIC_IP:3030" > .env
             npm install
             npm run build:prod
             # aws s3 sync dist s3://udapeople-project
-            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
-      # - destroy-environment  
-      # - revert-migrations   
-      # Here's where you will add some code to rollback on failure      
+            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:5} --recursive
+#       # Here's where you will add some code to rollback on failure      
                     
   deploy-backend:
     docker:
-      - image:  mareimorsy/aws-node
+      - image: mareimorsy/aws-node
     steps:
       - checkout
-#      - install_awscli
-#      - install_ansible
-#      - install_nodejs 
-     # - install_dependencies             
       - add_ssh_keys:
           fingerprints: ["79:1b:93:8b:e3:ca:fe:be:61:26:31:42:dd:c0:51:cb"]
-      - attach_workspace:
-          at: ~/
-      - restore_cache:
-          keys: [backend-build]
       - run:
           name: Deploy backend
           command: |
+            export TYPEORM_HOST=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+            echo $TYPEORM_HOST >> .circleci/ansible/inventory.txt
             cd backend
             npm i
             npm run build
-            echo "TYPEORM_ENTITIES=./dist/modules/domain/**/*.entity{.ts,.js}" > .env
-            echo "TYPEORM_HOST=${TYPEORM_HOST}" >> .env
-            echo "TYPEORM_PORT=${TYPEORM_PORT}" >> .env
-            echo "TYPEORM_USERNAME=${TYPEORM_USERNAME}" >> .env
-            echo "TYPEORM_PASSWORD=${TYPEORM_PASSWORD}" >> .env
-            echo "TYPEORM_DATABASE=${TYPEORM_DATABASE}" >> .env
-            echo "TYPEORM_MIGRATIONS_DIR=./dist/migrations" >> .env
-            echo "TYPEORM_MIGRATIONS=./dist/migrations/*.ts" >> .env
-            tar -czf artifact.tar.gz dist/* package* .env
+            tar -czf artifact.tar.gz dist/* package*
             cp artifact.tar.gz ~/project/.circleci/ansible/roles/deploy/artifact.tar.gz
             ls ../.circleci/ansible/roles/deploy/
             cd ../.circleci/ansible
-            cat inventory.txt
             ansible-playbook -i inventory.txt deploy-backend.yml
-      #- destroy-environment  
-      #- revert-migrations   
- 
+      # Here's where you will add some code to rollback on failure  
+
   smoke-test:
     docker:
-      - image:  mareimorsy/aws-node
+      - image: amazon/aws-cli
     steps:
-      - checkout
+      # - checkout
       - run:
           name: Backend smoke test.
           command: |
-            echo "${CIRCLE_WORKFLOW_ID:0:7}"
-            BACKEND_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --query=Reservations[].Instances[].PublicIpAddress --output text)
-            API_URL="http://${BACKEND_IP}:3030"
-            echo "${API_URL}"
-            if curl -s "${API_URL}/api/status" | grep "ok"
+            export BACKEND_PUBLIC_IP=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+            
+            # URL="http://$BACKEND_PUBLIC_IP:3030/api/status"
+            URL="http://g00gle.com"
+            if curl -s --head ${URL}
             then
               echo "It worked!"
               exit 0
             else
-              echo "It failed!"
-              exit 1
-            fi
-      - run:
-          name: Frontend smoke test.
-          command: |
-            FRONTEND_URL=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/#/employees
-            echo ${FRONTEND_URL} 
-            if curl -s ${FRONTEND_URL} | grep "Welcome"
-            then
-              echo "It worked!"
-              exit 0
-            else
-              echo "It failed!"
+              echo "Rolling Back"
               exit 1
             fi
       - notify_on_failure
-      #- notify_on_success
-      #- destroy-environment
-      - revert-migrations       
+      - destroy_environment
 
   cloudfront-update:
     docker:
@@ -391,35 +299,33 @@ jobs:
                       list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
                       --no-paginate --output text)
             echo "Old Wokflow ID: $OLD_WORKFLOW_ID"
-            curl -k https://kvdb.io/rHHiyAHyXFsG4EDRPANWj/old_workflow_id -d "${OLD_WORKFLOW_ID}"
+            curl -k https://kvdb.io/${KVDB_BUCKET}/old_workflow_id -d "${OLD_WORKFLOW_ID}"
       - run:
           name: Update cloudfront distribution
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/cloudfront.yml \
-              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
+              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:5}" \
               --stack-name InitialStack
-      #- destroy-environment
-      - revert-migrations
-
   cleanup:
     docker:
       - image: mareimorsy/aws-node
     steps:
       - checkout
       - run:
-          name: Remove old stacks
+          name: Remove old stacks and files
           command: |
-            export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
+            export STACKS=($(aws cloudformation list-stacks \
+                --query "StackSummaries[*].StackName" \
                 --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
-            export OldWorkflowID=$(curl --insecure https://kvdb.io/rHHiyAHyXFsG4EDRPANWj/old_workflow_id)
-            echo Old Workflow ID: $OldWorkflowID 
             echo Stack names: "${STACKS[@]}"
+            export OldWorkflowID=$(curl --insecure https://kvdb.io/${KVDB_BUCKET}/old_workflow_id)
+            echo Old Workflow ID: $OldWorkflowID 
             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
             then
               aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
-              aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
-              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
+              aws cloudformation delete-stack --stack-name "backend-${OldWorkflowID}"
+              aws cloudformation delete-stack --stack-name "frontend-${OldWorkflowID}"
             fi
             
 workflows:
@@ -438,7 +344,7 @@ workflows:
       - deploy-infrastructure:
           requires: [test-frontend, test-backend, scan-frontend, scan-backend]
           filters:
-            branches:
+            branches: 
               only: [main]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
